stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - terraform init

plan-job:   
  stage: test   
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - terraform init
    - terraform plan
    


apply-job:      
  stage: deploy
  script:
    - terraform init
    - terraform apply -auto-approve
